-- Run this once in Supabase SQL Editor.
create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  name text not null,
  trade_type text not null default 'Trade',
  rating integer not null check (rating between 1 and 5),
  review text not null,
  created_at timestamptz not null default now()
);

alter table public.reviews enable row level security;

drop policy if exists "Anyone can read reviews" on public.reviews;
create policy "Anyone can read reviews"
on public.reviews for select
to anon
using (true);

drop policy if exists "Anyone can add reviews" on public.reviews;
create policy "Anyone can add reviews"
on public.reviews for insert
to anon
with check (true);

-- Optional database-level duplicate protection by exact name.
create unique index if not exists reviews_name_unique_ci
on public.reviews (lower(name));
